openapi: 3.0.0
info:
  title: Product catalog
  description: Documentation for product catalog API
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Retrieve products
      description: Retrieves a list of products.
      parameters:
        - name: category
          in: query
          description: Category of the products (optional)
          schema:
            type: string
        - name: price
          in: query
          description: Price of the products (optional)
          schema:
            type: string
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sku:
                      type: string
                      description: The product's SKU
                      example: "000003"
                    name:
                      type: string
                      description: The product's name
                      example: "SUV Vehicle, high end"
                    category:
                      type: string
                      description: The product's category
                      example: "vehicle"
                    price:
                      type: object
                      properties:
                        original:
                          type: number
                          format: float
                          example: 250000
                        final:
                          type: number
                          format: float
                          example: 175000
                        discount_percentage:
                          type: number
                          format: float
                          nullable: true
                          example: "30%"
                        currency:
                          type: string
                          example: "USD"
        '404':
          description: No products found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating no products found
